spring.application.name=notification-service

server.port=8084

gcp.project-id=project-d49b9533-3df1-44c3-ae8
gcp.pubsub.transaction.completed.subscription=transaction.completed-sub
gcp.pubsub.transaction.refunded.subscription=transaction.refunded-sub
gcp.pubsub.transaction.otp.generated.subscription=transaction.otp.generated-sub
gcp.pubsub.fraud.detected.subscription=fraud.detected-sub
gcp.pubsub.payment.failed.subscription=payment.failed-sub
gcp.pubsub.payment.completed.subscription=payment.completed-sub