spring.application.name=transaction-service
server.port=8082

accounts.service.url=http://localhost:8081

gcp.project-id=project-d49b9533-3df1-44c3-ae8

gcp.pubsub.transaction.initiated.topic=transaction.initiated
gcp.pubsub.transaction.completed.topic=transaction.completed
gcp.pubsub.transaction.refunded.topic=transaction.refunded
gcp.pubsub.fraud.detected.topic=fraud.detected
gcp.pubsub.transaction.otp.generated.topic=transaction.otp.generated

gcp.pubsub.fraud.check.clean.subscription=fraud.check.clean-sub
gcp.pubsub.verification.required.subscription=verification.required-sub

spring.datasource.url=jdbc:postgresql://ep-damp-cell-a4igy0yp-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

