spring.application.name=payment-service
server.port=8085

spring.datasource.url=jdbc:postgresql://ep-damp-cell-a4igy0yp-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

razorpay.access.key=${RAZORPAY_ACCESS_KEY}
razorpay.secret.key=${RAZORPAY_SECRET_KEY}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}


gcp.project-id=project-d49b9533-3df1-44c3-ae8
gcp.pubsub.payment.failed.topic=payment.failed
gcp.pubsub.payment.failed.subscription=payment.failed-sub
gcp.pubsub.payment.completed.topic=payment.completed
gcp.pubsub.payment.completed.subscription=payment.completed-sub