spring.application.name=fraud-service

server.port=8083

spring.data.redis.host=localhost
spring.data.redis.port=6379

gcp.project-id=project-d49b9533-3df1-44c3-ae8
gcp.pubsub.verification.required.topic=verification.required
gcp.pubsub.fraud.check.clean.topic=fraud.check.clean
gcp.pubsub.transaction.initiated.subscription=transaction.initiated-sub

accounts.service.url=http://localhost:8081

fraud.max-transactions-per-minute=5
fraud.suspicious-amount-multiplier=3.0
fraud.max-balance-percentage=0.90